# Generated by Django 4.2.3 on 2023-09-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('super_admin', 'super_admin'), ('admin', 'admin'), ('user', 'user')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('Two', 'Two Wheeler'), ('Three', 'Three Wheeler'), ('Four', 'Four Wheeler')], max_length=10)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_description', models.TextField()),
            ],
        ),
    ]
