# Generated by Django 4.2.3 on 2023-09-20 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_vehicle', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'permissions': [('can_update_vehicle', 'Can Update Vehicle'), ('can_delete_vehicle', 'Can Delete Vehicle')]},
        ),
    ]
