# Generated by Django 4.2.3 on 2023-09-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_vehicle', '0003_alter_vehicle_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_user', 'super_user'), ('admin', 'admin'), ('user', 'user')], max_length=20),
        ),
    ]
