# Generated by Django 4.2.3 on 2023-09-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_vehicle', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'super_admin'), ('admin', 'admin'), ('user', 'user')], max_length=20),
        ),
    ]
