# Generated by Django 4.2.3 on 2023-09-21 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_vehicle', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='null', max_length=200),
        ),
    ]
