# Generated by Django 4.2.3 on 2023-09-21 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_vehicle', '0006_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={},
        ),
    ]
